In [1]:
import matplotlib.pyplot as plt
import numpy as np
from random import randint
from time import *
time=perf_counter
start_time = time()

#Everything before "image = plt.imread(image)" is just on ellas request, before we actually submit it would be replaced
choice = input("Tall (T) or Wide (W)")
while choice.upper() != "T" and choice.upper() != "W":
    choice = input("Tall (T) or Wide (W)")
if choice.upper() == "T":
    ella_hugo_BOSS_ulbrich = randint(1,22)
    if ella_hugo_BOSS_ulbrich == 7:
        image = "Tall2.jpg"
        #Thales: 80 wide, 134 high
    else:
        image = "Tall1.jpg"
        #Ella: 80 wide, 155 high
else:
    image = "aWide.jpg"
    #164 wide, 80 high

image = plt.imread(image)
scale = 10
WHITE = np.array([255,255,255])
def notwhite(cell):
    return (cell!=WHITE).all()
    return np.linalg.norm(cell-WHITE)<10
size = max(image.shape[0],image.shape[1])*scale
canvas = np.zeros((size, int(size*1.5), image.shape[2]), dtype=np.uint8)
canvas += 255
f = int(0.5*image.shape[1])
start_x = int(0.6*image.shape[1])
start_y = int(-0.9*image.shape[0])
minimum_x = 1<<62
maximum_x = -(1<<62)
minimum_y = 1<<62
maximum_y = -(1<<62)
for y in range(image.shape[0]):
    for x in range(image.shape[1]):
        colour = image[y, x]
        old_x = x + start_x
        old_y = y + start_y

        new_x = -int((f * old_x) / (old_x - f))
        new_y = int((old_y / old_x) * new_x)

        old_y_index = (size // 2) + old_y
        old_x_index = (3 * size // 4) + old_x
        new_y_index = (size // 2) + new_y
        new_x_index = (3 * size // 4) + new_x

        if 0 <= old_y_index < size and 0 <= old_x_index < canvas.shape[1]:
            canvas[old_y_index, old_x_index] = colour

        if 0 <= new_y_index < size and 0 <= new_x_index < canvas.shape[1]:
            canvas[new_y_index, new_x_index] = colour

        # Update minimum and maximum values
        minimum_x = min(minimum_x, new_x_index)
        maximum_x = max(maximum_x, new_x_index)
        minimum_y = min(minimum_y, new_y_index)
        maximum_y = max(maximum_y, new_y_index)
        #for dy in range(-10, 11):
        #    for dx in range(-10, 11):
        #        try:
        #            canvas[(size//2)+new_y+dy, (3*size//4)+new_x+dx] = colour
        #        except:
        #            continue
def fix_row(row, left, right):
    global canvas
    filled_in = []
    for i in range(left, right+1):
        if (notwhite(canvas[row][i])):
            filled_in.append(i)
    #filled_in is already sorted
    n = len(filled_in)
    if n<2:
        #skip operation: insufficient data
        return
    left = filled_in[0]
    right = filled_in[-1]
    curind = 0
    for i in range(left+1, right):
        if filled_in[curind+1]==i:
            curind+=1
        le = filled_in[curind]
        ri = filled_in[curind+1]
        actual_colour = canvas[row][le]*((ri-i)/(ri-le)) + canvas[row][ri]*((i-le)/(ri-le))
        #print(canvas[row][le], canvas[row][ri], le, i, ri, actual_colour)
        #above line takes the linear combination of the colours which are filled in on the left and right
        canvas[row][i] = actual_colour

def fix_col(col, left, right):
    global canvas
    filled_in = []
    for i in range(left, right+1):
        if (notwhite(canvas[i][col])):
            filled_in.append(i)
    #filled_in is already sorted
    n = len(filled_in)
    if n<2:
        #skip operation: insufficient data
        return
    left = filled_in[0]
    right = filled_in[-1]
    curind = 0
    for i in range(left+1, right):
        if filled_in[curind+1]==i:
            curind+=1
        le = filled_in[curind]
        ri = filled_in[curind+1]
        actual_colour = canvas[le][col]*((ri-i)/(ri-le)) + canvas[ri][col]*((i-le)/(ri-le))
        #print(canvas[row][le], canvas[row][ri], le, i, ri, actual_colour)
        #above line takes the linear combination of the colours which are filled in on the left and right
        canvas[i][col] = actual_colour
print(time()-start_time)
for col in range(minimum_x, maximum_x+1):
    fix_col(col, minimum_y, maximum_y)
for row in range(minimum_y, maximum_y+1):
    fix_row(row, minimum_x, maximum_x)
plt.imshow(canvas, extent=[-size*1.5, size*1.5, -size, size])
plt.xlim(-size*1.5, size*1.5)
plt.ylim(-size, size)
plt.axvline(x=0)
plt.scatter(f, 0, color='red', marker='*')
plt.scatter(-f, 0, color='red', marker='*')
print('exec time:',time()-start_time)

Tall (T) or Wide (W)T


FileNotFoundError: [Errno 2] No such file or directory: 'Tall1.jpg'

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from random import randint
from time import perf_counter

# === Image Selection (outside of timed portion) ===
choice = input("Tall (T) or Wide (W): ")
while choice.upper() not in ("T", "W"):
    choice = input("Tall (T) or Wide (W): ")

if choice.upper() == "T":
    if randint(1, 22) == 7:
        image_file = "Tall2.jpg"  # Thales: 80 wide, 134 high
    else:
        image_file = "Tall1.jpg"  # Ella: 80 wide, 155 high
else:
    image_file = "aWide.jpg"      # 164 wide, 80 high

# Read the image (assumed to be RGB)
image = plt.imread(image_file)

# ---- Start timing AFTER user input is taken ----
start_time = perf_counter()

# === Setup and Precalculations ===
scale = 6
# Define white in RGB
WHITE = np.array([255, 255, 255])

# Image dimensions
img_height, img_width, channels = image.shape

# Derived constants (as in the original code)
f = int(0.5 * img_width)
start_x = int(0.6 * img_width)
start_y = int(-0.9 * img_height)

# Canvas dimensions and initialization
size = max(img_height, img_width) * scale   # This is used as canvas height
canvas_height = size
canvas_width = int(size * 1.5)                # Canvas width is 1.5 times size
canvas = np.full((canvas_height, canvas_width, channels), 255, dtype=np.uint8)

# === Vectorized Coordinate Transformation ===
# Create coordinate arrays for the image pixels.
yy, xx = np.indices((img_height, img_width))
# Compute shifted coordinates based on starting offsets.
old_x = xx + start_x
old_y = yy + start_y

# Compute projected "new" coordinates exactly as in the original, then cast to int.
new_x_float = - (f * old_x) / (old_x - f)
new_x = new_x_float.astype(int)
new_y_float = (old_y / old_x) * new_x_float
new_y = new_y_float.astype(int)

# Convert these to canvas indices.
# (Original offsets: y -> canvas_height//2, x -> 3*canvas_height//4)
old_y_index = (canvas_height // 2) + old_y
old_x_index = (3 * canvas_height // 4) + old_x
new_y_index = (canvas_height // 2) + new_y
new_x_index = (3 * canvas_height // 4) + new_x

# === Assign Pixels to Canvas with Validity Checks ===
# For the "old" pixels:
valid_old = (old_y_index >= 0) & (old_y_index < canvas_height) & \
            (old_x_index >= 0) & (old_x_index < canvas_width)
# For the "new" pixels.
valid_new = (new_y_index >= 0) & (new_y_index < canvas_height) & \
            (new_x_index >= 0) & (new_x_index < canvas_width)

# Vectorized assignment for each projection.
canvas[old_y_index[valid_old], old_x_index[valid_old]] = image[yy[valid_old], xx[valid_old]]
canvas[new_y_index[valid_new], new_x_index[valid_new]] = image[yy[valid_new], xx[valid_new]]

# === Compute Bounding Box for the New Image Projection Only ===
# Here we only use the "new" indices.
all_new_x = new_x_index[valid_new].ravel()
all_new_y = new_y_index[valid_new].ravel()

raw_min_x = int(all_new_x.min())
raw_max_x = int(all_new_x.max())
raw_min_y = int(all_new_y.min())
raw_max_y = int(all_new_y.max())

# We do not clip to 0-canvas if we want the physical bounds from the projection.
# (However, for the interpolation loop, we must use valid canvas slice indices.)
minimum_x = max(raw_min_x, 0)
maximum_x = min(raw_max_x, canvas_width - 1)
minimum_y = max(raw_min_y, 0)
maximum_y = min(raw_max_y, canvas_height - 1)

# === Interpolation Functions Restricted to New Image Bounding Box ===
def fix_row(row, left, right):
    """
    For a given row in the canvas, interpolate between non-white pixels for columns
    from left to right. Only the segment between the first and last non-white cell
    encountered (within this provided bounding box) is modified.
    """
    cols = np.arange(left, right + 1)
    row_slice = canvas[row, left:right+1]  # shape: (width, channels)
    # Non-white: at least one channel is not 255.
    mask = (row_slice != 255).any(axis=1)
    if mask.sum() < 2:
        return  # Not enough non-white pixels to interpolate.

    # Get only the non-white indices from the bounding box.
    filled_cols = cols[mask]
    seg_left = filled_cols[0]
    seg_right = filled_cols[-1]

    # Interpolate only between seg_left and seg_right.
    interp_cols = np.arange(seg_left, seg_right + 1)
    for ch in range(channels):
        xp = filled_cols
        fp = row_slice[mask, ch]
        interpolated = np.interp(interp_cols, xp, fp)
        canvas[row, interp_cols, ch] = np.around(interpolated).astype(np.uint8)

def fix_col(col, top, bottom):
    """
    For a given column in the canvas, interpolate between non-white pixels for rows
    from top to bottom. Only the segment between the first and last non-white cell
    encountered (within this provided bounding box) is modified.
    """
    rows = np.arange(top, bottom + 1)
    col_slice = canvas[top:bottom+1, col]  # shape: (height, channels)
    mask = (col_slice != 255).any(axis=1)
    if mask.sum() < 2:
        return  # Not enough non-white pixels to interpolate.

    filled_rows = rows[mask]
    seg_top = filled_rows[0]
    seg_bottom = filled_rows[-1]

    interp_rows = np.arange(seg_top, seg_bottom + 1)
    for ch in range(channels):
        xp = filled_rows
        fp = col_slice[mask, ch]
        interpolated = np.interp(interp_rows, xp, fp)
        canvas[interp_rows, col, ch] = np.around(interpolated).astype(np.uint8)

# === Apply Interpolation in the New Image Bounding Box ===
for col in range(minimum_x, maximum_x + 1):
    fix_col(col, minimum_y, maximum_y)

for row in range(minimum_y, maximum_y + 1):
    fix_row(row, minimum_x, maximum_x)

print("Total processing time:", perf_counter() - start_time)

# === Plot the Result ===
plt.imshow(canvas, extent=[-size * 1.5, size * 1.5, -size, size])
plt.xlim(-size * 1.5, size * 1.5)
plt.ylim(-size, size)
plt.axvline(x=0)
plt.scatter(f, 0, color='red', marker='*')
plt.scatter(-f, 0, color='red', marker='*')
plt.show()

Tall (T) or Wide (W):  W


Total processing time: 0.05050609994214028


(785, 1189)

In [ ]:
minimum_x,maximum_x

(922, 1104)

In [ ]:
minimum_y,maximum_y

(700, 1470)

In [ ]:
row=1
le,i,ri=113,115,496
print(canvas[row][le], canvas[row][ri])
print(canvas[row][le]*((ri-i)/(ri-le)) + canvas[row][ri]*((i-le)/(ri-le)))

[255 255 255] [255 255 255]
[255. 255. 255.]


In [ ]:
(ri-i)/(ri-le)

0.9947780678851175

In [ ]:
canvas[row][le]*27/28

array([8.17857143, 8.17857143, 8.17857143])

In [ ]:
canvas[row][le]*27

array([229, 229, 229], dtype=uint8)

In [ ]:
a=np.array([1,2,3])
b=np.array([1,2,3])

In [ ]:
a==b

array([ True,  True,  True])

In [ ]:
canvas

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]